{
 "title": "ExceedsAt Threshold",
 "time": { "from": "now-25s", "to": "now" },
 "templating": {
  "list": [
   { "name": "threshold", "label": "Threshold", "query": "59.9675" },
   {
    "name": "query",
    "label": "Query",
    "query": "MovingAvg(KalmanFilter(TVA_TESTDEVICE:ABBF))"
   }
  ]
 },
 "panels": [
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "queryText": "Label(Freq, ${query}); \nLabel(Exceed Points, ExceedsAt(${threshold}, ${query})); \nLabel(Falls Below Points, ExceedsAt(${threshold}, true, ${query}));\nLabel(threshold, eval(1, { ${threshold} }, ${query}));\nfullResolutionQuery"
    }
   ]
  },
  {
   "title": "Exceeded Table",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "queryText": "Label(ExceedsAt, ExceedsAt(${threshold}, false, true, ${query}));\nfullResolutionQuery"
    }
   ]
  },
  {
   "title": "Exeeds Time",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "queryText": "Label('͏ ͏ ͏ ͏ ͏ ͏ ͏ ͏ ͏ ͏͏ ͏', ExceedsAt(${threshold}, false, true, true, ${query}));\nfullResolutionQuery"
    }
   ]
  }
 ]
}